export const WINNER_SET = "WINNER_SET";

export const BOARD_CELL_SET = "BOARD_CELL_SET";
export const BOARD_RESET = "BOARD_RESET";

export const PIECE_REMOVE = "PIECE_REMOVE";
export const PIECE_SELECT = "PIECE_SELECT";

export const TURN_SET = "TURN_SET";
export const WINNING_COMBINATION_SET = "WINNING_COMBINATION_SET";
